[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[project]
name = "python-project"
version = "0.1.0"
description = "A Python project template"
authors = [{ name = "Hassan Pouralijan", email = "pouralijan@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = []

[project.optional-dependencies]
dev = ["ruff>=0.1.0", "pytest>=7.0.0", "pre-commit>=3.0.0", "mypy>=1.0.0"]
